### ISSUE TITLE
某些版本，移动 “最近阅读” 时，页面会跟随滚动

### ISSUE THREAD

**Issue by imfycc** [yued-fe/inertia#3]
移动端：
Android Chrome 56、Android Webview 56及以上版本的浏览器，移动 “最近阅读” 时，页面会跟随滚动

问题原由：
https://www.chromestatus.com/features/5093566007214080

**Comment by zhangxinxu** [comment]
感谢反馈，我明天修一下。

**Comment by zhangxinxu** [comment]
已修复~
